baseURL: https://example.com
languageCode: en-us
title: Portfolio of Xinge Zhang
theme: "yourfolio"
disableKinds: [RSS, taxonomy, taxonomyTerm]
googleAnalytics: UA-XXXXX-Y

# Menu items
menu:
  main:
  - name: Home
    weight: 1
    url: /home
  - name: Experience
    weight: 2
    url: /about
  - name: Skills
    weight: 3
    url: /skill
  - name: Project
    weight: 4
    url: /projects
  - name: Contact
    weight: 5
    url: /contact

# Custom params
params:
  env: development
  logoImage: img/logo.png
  logoImageAlt: Yourfolio Theme brand logo
